return {}

-- return {
--     'saghen/blink.cmp',
--     event = "InsertEnter",
--     -- optional: provides snippets for the snippet source
--     dependencies = { { 'L3MON4D3/LuaSnip', version = 'v2.*' }, 'rafamadriz/friendly-snippets' },
--     version = '*',
--     opts = {
--         snippets = { preset = 'luasnip' },
--         -- 'default' for mappings similar to built-in completion
--         -- 'super-tab' for mappings similar to vscode (tab to accept, arrow keys to navigate)
--         -- 'enter' for mappings similar to 'super-tab' but with 'enter' to accept
--         -- See the full "keymap" documentation for information on defining your own keymap.
--         keymap = {
--             preset = 'default',
--             ['<C-j>'] = { 'select_next', 'fallback' },
--             ['<C-k>'] = { 'select_prev', 'fallback' },
--             -- ['<C-l>'] = { 'snippet_forward', 'fallback' },
--             -- ['<C-h>'] = { 'snippet_backward', 'fallback' },
--             ['<C-i>'] = { 'fallback' },
--
--             cmdline = {
--                 preset = 'default',
--                 ['<C-j>'] = { 'select_next', 'fallback' },
--                 ['<C-k>'] = { 'select_prev', 'fallback' },
--
--                 ['<CR>'] = { 'select_and_accept', 'fallback' },
--             }
--             --     ['<Tab>'] = { 'select_next', 'fallback' },
--             --     ['<S-Tab>'] = { 'select_prev', 'fallback' },
--             -- }
--             -- -- show with a list of providers
--             -- ['<C-space>'] = { function(cmp) cmp.show({ providers = { 'snippets' } }) end },
--         },
--
--         completion = {
--             menu = { auto_show = function(ctx) return ctx.mode ~= 'cmdline' end },
--             documentation = {
--                 auto_show = true,
--                 auto_show_delay_ms = 500,
--                 window = { border = 'single' }
--             },
--             list = {
--                 selection = {
--                     preselect = true,
--                     auto_insert = function(ctx) return ctx.mode == 'cmdline' end
--                 }
--             }
--         },
--         signature = { window = { border = 'single' } },
--
--         -- Default list of enabled providers defined so that you can extend it
--         -- elsewhere in your config, without redefining it, due to `opts_extend`
--         sources = {
--             default = { 'lsp', 'path', 'snippets', 'buffer' },
--         },
--     },
--     opts_extend = { "sources.default" }
-- }
