return {}

-- return {
--     'saghen/blink.cmp',
--     -- optional: provides snippets for the snippet source
--     dependencies = 'rafamadriz/friendly-snippets',
--     version = '*',
--     opts = {
--         -- 'default' for mappings similar to built-in completion
--         -- 'super-tab' for mappings similar to vscode (tab to accept, arrow keys to navigate)
--         -- 'enter' for mappings similar to 'super-tab' but with 'enter' to accept
--         -- See the full "keymap" documentation for information on defining your own keymap.
--         keymap = {
--             preset = 'default',
--             ['<C-j>'] = { 'select_next', 'fallback' },
--             ['<C-k>'] = { 'select_prev', 'fallback' },
--
--             -- -- show with a list of providers
--             -- ['<C-space>'] = { function(cmp) cmp.show({ providers = { 'snippets' } }) end },
--         },
--
--
--         completion = {
--             menu = { auto_show = function(ctx) return ctx.mode ~= 'cmdline' end },
--             documentation = {
--                 auto_show = true,
--                 auto_show_delay_ms = 500,
--                 window = { border = 'single' }
--             }
--         },
--         signature = { window = { border = 'single' } },
--
--         -- Default list of enabled providers defined so that you can extend it
--         -- elsewhere in your config, without redefining it, due to `opts_extend`
--         sources = {
--             default = { 'lsp', 'path', 'snippets', 'buffer' },
--         },
--     },
--     opts_extend = { "sources.default" }
-- }

-- return {
--     -- add blink.compat
--     {
--         'saghen/blink.compat',
--         -- use the latest release, via version = '*', if you also use the latest release for blink.cmp
--         version = '*',
--         -- lazy.nvim will automatically load the plugin when it's required by blink.cmp
--         lazy = true,
--         dependencies = {
--             { 'L3MON4D3/LuaSnip', version = 'v2.*' },
--             "rafamadriz/friendly-snippets",
--         },
--         -- make sure to set opts so that lazy.nvim calls blink.compat's setup
--         opts = {
--             snippets = { preset = 'luasnip' },
--             -- ensure you have the `snippets` source (enabled by default)
--             sources = {
--                 default = { 'lsp', 'path', 'snippets', 'buffer' },
--             },
--         }
--     },
--     --
--     {
--         'saghen/blink.cmp',
--         version = '0.*',
--         dependencies = {
--             -- add source
--             { 'dmitmel/cmp-digraphs' },
--         },
--         sources = {
--             -- remember to enable your providers here
--             default = { 'lsp', 'path', 'snippets', 'buffer', 'digraphs' },
--             providers = {
--                 -- create provider
--                 digraphs = {
--                     name = 'digraphs', -- IMPORTANT: use the same name as you would for nvim-cmp
--                     module = 'blink.compat.source',
--
--                     -- all blink.cmp source config options work as normal:
--                     score_offset = -3,
--
--                     -- this table is passed directly to the proxied completion source
--                     -- as the `option` field in nvim-cmp's source config
--                     --
--                     -- this is NOT the same as the opts in a plugin's lazy.nvim spec
--                     opts = {
--                         -- this is an option from cmp-digraphs
--                         cache_digraphs_on_start = true,
--                     },
--                 },
--             },
--         },
--     },
-- }
