return {
    -- "glepnir/lspsaga.nvim",
    -- event = "LspAttach",
    -- dependencies = { { "nvim-tree/nvim-web-devicons" } },
    -- commit = "496ea37208fdd670751f3b1b04b5d2cfdb12af91",
    -- config = function()
    --     local keymap = vim.keymap.set
    --
    --     -- Code action
    --     keymap({ "n", "v" }, "<leader>la", "<cmd>Lspsaga code_action<CR>")
    --     -- Rename all occurrences of the hovered word for the selected files
    --     --
    --     keymap("n", "<leader>rn", "<cmd>Lspsaga rename<CR>")
    --     --
    --     -- Toggle outline
    --     keymap("n", "<leader>lo", "<cmd>Lspsaga outline<CR>")
    --
    --     keymap("n", "K", "<cmd>Lspsaga hover_doc<CR>")
    --
    --     keymap("n", "[d", "<cmd>Lspsaga diagnostic_jump_prev<CR>")
    --     keymap("n", "]d", "<cmd>Lspsaga diagnostic_jump_next<CR>")
    --     require('lspsaga').setup({
    --         lightbulb = {
    --             enable = false,
    --         },
    --     })
    -- end
}
